version: 2

updates:
  - package-ecosystem: nuget
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    commit-message:
      prefix: deps
    groups:
      nuget-minor-patch:
        update-types: [minor, patch]
  - package-ecosystem: github-actions
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: saturday
      time: "08:30"
      timezone: Europe/Rome
    open-pull-requests-limit: 5
    commit-message:
      prefix: ci
    groups:
      actions-minor-patch:
        update-types: [minor, patch]
