name: Bug Report
description: Report a defect or regression.
labels:
  - bug
  - needs-triage
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What is happening, and what did you expect instead?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps To Reproduce
      description: Provide concrete reproduction steps.
      placeholder: |
        1. Open...
        2. Click...
        3. Observe...
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: App version, OS, and anything else relevant.
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Additional Context
      description: Logs, screenshots, trust-state details, or anything else helpful.
